### PR TITLE
here we go again

### PR DESCRIPTION
**Pull request by awakened-game**
here we go again

### CODE REVIEW

**Comment by ThisTestUser** [comment]
Well, this is how I once did it.

**Comment by awakened-game** [comment]
@ThisTestUser yeah, i figured it out before, i update mine, then reset the local head to remove my changes, then pull from my fork, then patch a fresh mcp copy and im done, then i make my changes again, which include disguising it as vanilla 1.8, even in the debug screen :smile:

**Comment by ThisTestUser** [comment]
Well, none of us have been able to apply the minecraft.patch, and did it work for you?

**Comment by awakened-game** [comment]
@ThisTestUser yeah, i did `git apply --reject --whitespace=fix <file>`

**Comment by awakened-game** [comment]
@ThisTestUser holy crap, i just found a public 1.9 client already :scream:

**Comment by awakened-game** [comment]
@ThisTestUser wow.... this is unreal... its not obfuscated :laughing:

**Comment by awakened-game** [comment]
@ThisTestUser either this is full unobfuscated minecraft 1.9, or its 1.8 with a protocol hack...

**Comment by ThisTestUser** [comment]
But how do you compile it? Can Eclipse do it?

**Comment by awakened-game** [comment]
@ThisTestUser compile what? wurst? yeah i use eclipse Neon

**Comment by ThisTestUser** [comment]
Why does it say the main class is missing if I try to compile the client? I have the .class file, and I even used the .class file from the 2.19 client (I only replaced the files that changed).

**Pull request merged**
